package com.deepseekharness.app.util;
import java.util.List;
// Generated by tools/generate-builtin-plugins.py; edit assets/builtin-plugins.json.
public final class BuiltinPluginRegistry {
    private BuiltinPluginRegistry() { }
    public static final List<String> DEFAULT = List.of("dsh-device-shell-guide", "dsh-task-notifier", "dsh-status-overlay", "dsh-web-mobile", "dsh-computer-use-android", "dsh-auto-review", "dsh-tool-vscreen", "dsh-peak-chip", "dsh-batch-tool-calls", "dsh-any-background", "dsh-session-health", "dsh-subagent-model-picker");
    public static final List<String> SIGNED = List.of("dsh-device-shell-guide", "dsh-task-notifier", "dsh-status-overlay", "dsh-web-mobile", "dsh-computer-use-android", "dsh-auto-review", "dsh-tool-vscreen", "dsh-app-integration", "dsh-peak-chip", "dsh-batch-tool-calls", "dsh-any-background", "dsh-session-health", "dsh-subagent-model-picker");
    public static final List<String> OFFICIAL = List.of("@deepseek-ai/dsh-base", "@deepseek-ai/dsh-web-app");
    public static final List<String> INTERNAL = List.of("dsh-app-integration", "@deepseek-ai/dsh-base", "@deepseek-ai/dsh-web-app");
    public static String guestDirectory(String name) {
        if (name == null) return "";
        return switch(name) {
            case "dsh-device-shell-guide" -> "/root/dsha-device-shell-guide";
            case "dsh-task-notifier" -> "/root/dsha-task-notifier";
            case "dsh-status-overlay" -> "/root/dsha-status-overlay";
            case "dsh-web-mobile" -> "/root/dsha-web-mobile";
            case "dsh-computer-use-android" -> "/root/dsha-computer-use-android";
            case "dsh-auto-review" -> "/root/dsha-auto-review";
            case "dsh-tool-vscreen" -> "/root/dsha-tool-vscreen";
            case "dsh-app-integration" -> "/root/dsha-app-integration";
            case "dsh-peak-chip" -> "/root/dsha-peak-chip";
            case "dsh-batch-tool-calls" -> "/root/dsha-batch-tool-calls";
            case "dsh-any-background" -> "/root/dsha-any-background";
            case "dsh-session-health" -> "/root/dsha-session-health";
            case "dsh-subagent-model-picker" -> "/root/dsha-subagent-model-picker";
            default -> "";
        };
    }
    public static String entrypoint(String name) {
        if (name == null) return "";
        return switch(name) {
            case "dsh-device-shell-guide" -> "lib/index.js";
            case "dsh-task-notifier" -> "lib/index.js";
            case "dsh-status-overlay" -> "lib/index.js";
            case "dsh-web-mobile" -> "lib/index.js";
            case "dsh-computer-use-android" -> "lib/index.js";
            case "dsh-auto-review" -> "lib/index.js";
            case "dsh-tool-vscreen" -> "lib/index.js";
            case "dsh-app-integration" -> "index.js";
            case "dsh-peak-chip" -> "lib/index.js";
            case "dsh-batch-tool-calls" -> "lib/index.js";
            case "dsh-any-background" -> "lib/index.js";
            case "dsh-session-health" -> "lib/index.js";
            case "dsh-subagent-model-picker" -> "lib/index.js";
            default -> "";
        };
    }
}
